name: Docker Image CI

on:
  schedule:
  - cron: "0 0 * * 1"
  push:
    branches: ['master']


jobs:
  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base: [buster]
        php: [7.4]
        type: [pimcore-node16, pimcore-c1]
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          cd ./${{ matrix.php }}/${{ matrix.base }}/${{ matrix.type }};
          docker build . --tag php-environments:${{ matrix.php }}-${{ matrix.base }}-${{ matrix.type }};
