name: Docker Image CI

on:
  schedule:
  - cron: "0 0 * * 1"
  push:
    branches: ['master']

env:
  REGISTRY: ghcr.io
  CONTAINER_IMAGE: ${{ env.REGISTRY }}/${{ github.repository }}

jobs:
  example_matrix:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        base: [buster]
        php: [7.4]
        type: [pimcore-node16, pimcore-c1]
    steps:
      - uses: actions/checkout@v3
      - name: Docker login to github packages
        run: |
          docker login -p ${{ secrets.GITHUB_TOKEN }} -u ${{ github.actor }} ${{ env.REGISTRY }}
      - name: Build the Docker image
        run: |
          cd ./${{ matrix.php }}/${{ matrix.base }}/${{ matrix.type }};
          docker build . --tag ${{ env.CONTAINER_IMAGE }}:${{ matrix.php }}-${{ matrix.base }}-${{ matrix.type }};
      - name: Push the Docker image
        run: |
          docker push ${{ env.CONTAINER_IMAGE }}:${{ matrix.php }}-${{ matrix.base }}-${{ matrix.type }};
